services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app-1
    restart: unless-stopped
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 80M
    environment:
      - APP_ENV=production
      - PORT=8080
      - INSTANCE_ID=1

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app-2
    restart: unless-stopped
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 80M
    environment:
      - APP_ENV=production
      - PORT=8080
      - INSTANCE_ID=2

  haproxy:
    image: haproxy:2.9-alpine
    container_name: haproxy-lb
    restart: unless-stopped
    ports:
      - "9999:80"
    networks:
      - payment-processor
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 70M
    depends_on:
      - app1
      - app2

  redis:
    image: redis:7-alpine
    container_name: redis
    command: >
      redis-server
      --maxmemory 120mb
      --maxmemory-policy allkeys-lru
      --appendonly no
      --save ""
      --tcp-backlog 128
      --tcp-keepalive 60
      --timeout 0
      --databases 1
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 120M

# volumes:
#   sqlite-data:
#     driver: local

networks:
  payment-processor:
    name: payment-processor
    driver: bridge
