services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app-1
    restart: unless-stopped
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 80M
    environment:
      - APP_ENV=production
      - PORT=8080
      - INSTANCE_ID=1

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app-2
    restart: unless-stopped
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 80M
    environment:
      - APP_ENV=production
      - PORT=8080
      - INSTANCE_ID=2

  haproxy:
    image: haproxy:2.9-alpine
    container_name: haproxy-lb
    restart: unless-stopped
    ports:
      - "9999:80"
    networks:
      - payment-processor
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 70M
    depends_on:
      - app1
      - app2

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: onecent
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 120M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d onecent"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
    driver: local

networks:
  payment-processor:
    name: payment-processor
    driver: bridge
